// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy7e72Sb1dD--JH6NVXwYcbD1qgnFMZsY',
    appId: '1:118478176076:android:f5f24d9bb7f95e3e6e59e9',
    messagingSenderId: '118478176076',
    projectId: 'flutterpracticeapp-f2478',
    storageBucket: 'flutterpracticeapp-f2478.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-UcodJSKqF_wLzAM66BCB102vS3PaOmQ',
    appId: '1:118478176076:ios:7afd148fbac4ff466e59e9',
    messagingSenderId: '118478176076',
    projectId: 'flutterpracticeapp-f2478',
    storageBucket: 'flutterpracticeapp-f2478.appspot.com',
    iosClientId: '118478176076-f0madtsg5qreaar1vc4qk4v05ovkb7l7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterpracticeapp.flutterpracticeapp',
  );
}
